#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

if xrandr | grep -q "HDMI1"
then
	bspc monitor HDMI1 -n 0 -d I II III IV V VI VII VIII IX X
else 
	bspc monitor LVDS1 -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a firefox floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/src/toolbox/fehbg
$HOME/src/toolbox/trayer.sh
